on: [push, pull_request]
name: lints

jobs:
  lints:
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
     LINTR_COMMENT_BOT: true
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("lintr")
        shell: Rscript {0}

      - name: Lint
        run: |
          lint_check <- lintr::lint_package(linters = lintr::with_defaults(object_usage_linter = NULL, line_length_linter = lintr::line_length_linter(100)))
          print(lint_check)
          if (length(lint_check) > 0) stop("There are still lints present")
        shell: Rscript {0}
